import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SecHeader from "@/components/layout/SecHeader";
import Ban from "@/components/ui/Ban";
const font = Montserrat({
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} overflow-x-hidden`}
      >
        <SecHeader />
        <Header />
        {children}
        <Ban />
        <Footer />
      </body>
    </html>
  );
}
